### ISSUE TITLE
Link Rot: damow.net

### ISSUE THREAD

**Issue by mide** [mide/mide.io#3]
Since June 10, `https://damow.net/` has served an expired TLS certificate. 

![screen shot 2017-06-19 at 9 49 34 pm](https://user-images.githubusercontent.com/546518/27312935-41fd0a30-5539-11e7-8ea9-f5ed7857cdf5.png)

And because of that, my link-rot-protection fails. 

![screen shot 2017-06-19 at 9 50 17 pm](https://user-images.githubusercontent.com/546518/27312958-5adf2c22-5539-11e7-9cab-0595ec97e697.png)

This issue tracks the workarounds (if any) and the removal of them.

**Comment by mide** [comment]
Oh, I found Damien's GitHub, mentioning him so he's aware: @themainframe.

**Comment by themainframe** [comment]
Sorted, thanks for the heads-up!

**Comment by mide** [comment]
Closed by d11283513776552c58db00d731da662c70ed5a48.

**Comment by mide** [comment]
Thanks @themainframe, we're good here!
